### ISSUE TITLE
Scale Up Lambdas not working in 5.10.2 after upgrading from 5.9.0.

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [philips-labs/terraform-aws-github-runner#3883]
After upgrading both my runner code and lambdas from `5.9.0` -to-> `5.10.2`, none of my scale-up lambdas were scaling up runners.  Looking a bit closer at the logs, I am now seeing this error:

```json
{
    "level": "WARN",
    "message": "Ignoring error: response.json(...).catch is not a function",
    "service": "service_undefined",
    "timestamp": "2024-05-01T14:03:59.036Z",
    "xray_trace_id": "1-66324bcd-b91f32230d4f1c5052a29617",
    "region": "us-east-1",
    "environment": "<REDACTED>",
    "aws-request-id": "d9b95d22-1a54-59ca-9a20-038e545cb1f1",
    "function-name": "<REDACTED>-scale-up",
    "module": "lambda.ts"
}
```
In the mean time, I have left my runner code on `5.10.2`, and downgraded the lambdas to `5.9.0` and that gets up and running again.  However this is not ideal, we would like to stay current as much as possible.

**Comment by commarla** [comment]
Hi, I got the same error upgrading from 5.10.0 to 5.10.2.

**Comment by bicefalo** [comment]
I just came here to report the same.

**Comment by nap** [comment]
https://github.com/philips-labs/terraform-aws-github-runner/issues/3870
